# Create environment:
# conda env create -f environment.yml
#
# Update environment when there is an change:
# conda env update -f environment.yml --prune
#
# Remove environment:
# conda remove --name pygame-kids --all
#
# Frequently used command:
# conda env list
# conda activate [env name: pygame-kids]
# pip list
#
name: picar-4wd
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.9
  - Cython
  - pip:
      - --requirement requirements.txt